# Generated by Django 2.1.5 on 2019-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='city')),
                ('abbreviation', models.CharField(default='', max_length=3, verbose_name='abbreviation')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, unique=True, verbose_name='country')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=3, verbose_name='code')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.City')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.Country')),
            ],
            options={
                'verbose_name': 'department',
                'verbose_name_plural': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('level', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='name')),
                ('code', models.CharField(default='', max_length=3, verbose_name='code')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.City')),
                ('country', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.Country')),
            ],
            options={
                'verbose_name': 'office',
                'verbose_name_plural': 'offices',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('cell', models.CharField(blank=True, default='', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.City')),
                ('department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Department')),
                ('group', models.ManyToManyField(blank=True, related_name='user_group', to='auth.Group')),
                ('level', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Level')),
                ('office', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
        migrations.AlterUniqueTogether(
            name='level',
            unique_together={('name', 'level')},
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.Office'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together={('name', 'city')},
        ),
    ]
