# Generated by Django 2.1.5 on 2019-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='force_password_change',
            field=models.BooleanField(default=True),
        ),
    ]
