# Generated by Django 2.1.5 on 2019-04-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_force_password_change'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='city',
        ),
        migrations.RemoveField(
            model_name='department',
            name='country',
        ),
        migrations.RemoveField(
            model_name='department',
            name='office',
        ),
        migrations.AddField(
            model_name='city',
            name='offices',
            field=models.ManyToManyField(blank=True, related_name='city_offices', to='profiles.Office'),
        ),
        migrations.AddField(
            model_name='office',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='office_departments', to='profiles.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='office',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='office',
            name='city',
        ),
    ]
