# Generated by Django 2.1.5 on 2019-03-13 11:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import memoir.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('date_archived', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date archived')),
                ('archiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archive',
                'verbose_name_plural': 'archives',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file', models.FileField(blank=True, help_text='Attach File', upload_to=memoir.models.file_upload_to_dispatcher, verbose_name='file')),
            ],
        ),
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True, verbose_name='is open')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('sent', models.BooleanField(default=False, verbose_name='sent')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('date_sent', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='date sent')),
                ('reference_number', models.CharField(db_index=True, max_length=23, unique=True, verbose_name='reference number')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='slug')),
                ('message', ckeditor.fields.RichTextField(verbose_name='memo body')),
                ('mem_type', models.CharField(choices=[('PUB', 'Public'), ('PVT', 'Private')], default='PUB', max_length=10, verbose_name='memo type')),
                ('mem_priority', models.CharField(choices=[('Very Urgent', 'Very Urgent'), ('Moderate', 'Moderate'), ('Normal', 'Normal')], default='Normal', max_length=15, verbose_name='memo priority')),
                ('commenting_required', models.BooleanField(default=True, verbose_name='commenting required')),
                ('receptors', models.ManyToManyField(blank=True, related_name='memo_receptors', to=settings.AUTH_USER_MODEL)),
                ('recipients', models.ManyToManyField(related_name='memo_recipients', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memo_from', to=settings.AUTH_USER_MODEL)),
                ('to', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memo_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'memo',
                'verbose_name_plural': 'memos',
                'ordering': ['-created'],
                'permissions': (('add_comment', 'Comment Memo'),),
            },
        ),
        migrations.CreateModel(
            name='MemoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memocomment_comment', to='memoir.Memo')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='memocomment_sub_comment', to='memoir.MemoComment')),
            ],
            options={
                'verbose_name': 'memo comment',
                'verbose_name_plural': 'memo comments',
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memoir.Memo'),
        ),
        migrations.AddField(
            model_name='archive',
            name='memo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='memoir.Memo'),
        ),
    ]
