# Generated by Django 2.1.5 on 2019-03-13 11:55

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fuel.models
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', ckeditor.fields.RichTextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fuel comment',
                'verbose_name_plural': 'fuel comments',
                'get_latest_by': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Moderate', 'Moderate'), ('Normal', 'Normal')], default='Normal', max_length=10, verbose_name='priority')),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel')], default='Petrol', max_length=10, verbose_name='fuel type')),
                ('date_requested', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date requested')),
                ('date_required', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='date of required')),
                ('amount', fuel.models.MinMaxFloat()),
                ('reason', models.TextField(default='', max_length=255, verbose_name='reason')),
                ('registration', models.CharField(default='', max_length=255, verbose_name='vehicle reg number')),
                ('origin', models.CharField(max_length=10, verbose_name='origin')),
                ('destination', models.CharField(max_length=10, verbose_name='destination')),
                ('reference_number', models.CharField(default='', max_length=50, verbose_name='reference number')),
                ('is_open', models.BooleanField(default=True, verbose_name='is open')),
                ('accepted', models.BooleanField(default=False, verbose_name='accepted')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manger', to=settings.AUTH_USER_MODEL)),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supervisor', to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='fuel_requester_city', to='profiles.City')),
                ('department', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.Department')),
                ('office', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='profiles.Office')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fuel',
                'verbose_name_plural': 'fuel',
                'ordering': ('-date_requested',),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comment_fuel', to='fuel.Fuel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comment_sub_comment', to='fuel.Comment'),
        ),
    ]
