# Generated by Django 2.1.5 on 2019-03-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuel',
            name='plus_vehicle',
            field=models.BooleanField(default=False, verbose_name='plus vehicle'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='registration',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='vehicle reg number'),
        ),
    ]
