# Generated by Django 2.1.5 on 2019-05-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_auto_20190315_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='destination',
            field=models.CharField(max_length=255, verbose_name='destination'),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='origin',
            field=models.CharField(max_length=255, verbose_name='origin'),
        ),
    ]
